Assignment 1


`








# Nancy Sinha 20MID0115

### 1. Assign your Name to variable name and Age to variable age. Make a Python program that prints your name and age.

In [7]:
name="NANCY SINHA"
age=20
print("Name",name,"\n Age",age)

Name NANCY SINHA 
 Age 20


### 2. X="Datascience is used to extract meaningful insights." Split the string

In [8]:
X="Datascience is used to extract meaningful insights."
X.split()


['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']

In [9]:
X.split("a")

['D', 't', 'science is used to extr', 'ct me', 'ningful insights.']

### 3. Make a function that gives multiplication of two numbers


In [10]:
def func(a,b):
    c=a*b
    print("The product of a and b is ",c)
n=int(input("Enter first number: "))
m=int(input("Enter second number: "))
func(n,m)



Enter first number: 5
Enter second number: 6
The product of a and b is  30


### 4. Create a Dictionary of 5 States with their capitals. also print the keys and values.

In [11]:
dict={'Himachal Pradesh':"Shimla","Bihar":"Patna","Punjab":"Chandigarh","Uttar Pradesh":"Lucknow","Jharkhand":"Ranchi"}
print(dict)
print(dict.keys(),dict.values())

{'Himachal Pradesh': 'Shimla', 'Bihar': 'Patna', 'Punjab': 'Chandigarh', 'Uttar Pradesh': 'Lucknow', 'Jharkhand': 'Ranchi'}
dict_keys(['Himachal Pradesh', 'Bihar', 'Punjab', 'Uttar Pradesh', 'Jharkhand']) dict_values(['Shimla', 'Patna', 'Chandigarh', 'Lucknow', 'Ranchi'])


In [12]:
#or
print(dict.keys())

dict_keys(['Himachal Pradesh', 'Bihar', 'Punjab', 'Uttar Pradesh', 'Jharkhand'])


In [13]:
dict.values()

dict_values(['Shimla', 'Patna', 'Chandigarh', 'Lucknow', 'Ranchi'])

### 5. Create a list of 1000 numbers using range function.


In [14]:
num=list(range(1,1001))
print(num)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 22

### 6. Create an identity matrix of dimension 4 by 4

In [15]:
import numpy as np
var2=np.eye(4,dtype="int")
var2

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### 7. Create a 3x3 matrix with values ranging from 1 to 9


In [16]:
import numpy as np
matrix =  np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 8. Create 2 similar dimensional array and perform sum on them.

In [17]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
print("1st array is ")
print(a1)
print("The dimension of a1 matrix",a1.ndim)
print("2nd array is ")
print(a2)
print("The dimension of a2 matrix",a2.ndim)
sum=a1+a2
print("the sum of 2 arrays ")
print(sum)
print("The dimension of sum matrix",sum.ndim)

1st array is 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The dimension of a1 matrix 2
2nd array is 
[[10 11 12]
 [13 14 15]
 [16 17 18]]
The dimension of a2 matrix 2
the sum of 2 arrays 
[[11 13 15]
 [17 19 21]
 [23 25 27]]
The dimension of sum matrix 2


### 9. Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both inclusive)

In [18]:
import pandas as pd

start_date = "2023-02-01"
end_date = "2023-03-01"

date_range = pd.date_range(start= start_date, end =  end_date)

for date in date_range:
    print(date)

2023-02-01 00:00:00
2023-02-02 00:00:00
2023-02-03 00:00:00
2023-02-04 00:00:00
2023-02-05 00:00:00
2023-02-06 00:00:00
2023-02-07 00:00:00
2023-02-08 00:00:00
2023-02-09 00:00:00
2023-02-10 00:00:00
2023-02-11 00:00:00
2023-02-12 00:00:00
2023-02-13 00:00:00
2023-02-14 00:00:00
2023-02-15 00:00:00
2023-02-16 00:00:00
2023-02-17 00:00:00
2023-02-18 00:00:00
2023-02-19 00:00:00
2023-02-20 00:00:00
2023-02-21 00:00:00
2023-02-22 00:00:00
2023-02-23 00:00:00
2023-02-24 00:00:00
2023-02-25 00:00:00
2023-02-26 00:00:00
2023-02-27 00:00:00
2023-02-28 00:00:00
2023-03-01 00:00:00


### 10. Given a dictionary, convert it into corresponding dataframe and display it dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}

In [20]:
import pandas as pd
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyundai'], 'Sales' : [250, 200, 240]}
print(dictionary)
df=pd.DataFrame(dictionary)
print(df)

{'Brand': ['Maruti', 'Renault', 'Hyundai'], 'Sales': [250, 200, 240]}
     Brand  Sales
0   Maruti    250
1  Renault    200
2  Hyundai    240
